### ISSUE TITLE
Use custom namespace for Brigadier arguments

### ISSUE THREAD

**Issue by unilock** [AlphaMode/CompactMachines-Fabric#4]
### I am not using performance mods.

- [X] Confirm

### Description

(this will be mostly copied from https://github.com/CammiePone/Arcanus/issues/60, as I don't know enough to completely understand the issue here)

Line 76 + 77 of [CompactMachines.java](https://github.com/AlphaMode/CompactMachines-Fabric/blob/1.18.x/src/main/java/dev/compactmods/machines/CompactMachines.java#L76) register your argument types `room_pos` and `upgrade_type` in the `minecraft:` namespace.
They should be registered in your own `compactmachines:` namespace instead. (i.e. `compactmachines:room_pos` and `compactmachines:upgrade_type`)
Using the reserved namespace (`minecraft:` or `brigadier:`) renders the mod incompatible with proxies running on top of Fabric servers, e.g. [Velocity](https://github.com/PaperMC/Velocity).

Related issue: https://github.com/PaperMC/Velocity/issues/789

### Mod Version

4.5.0a

### Fabric Version

Minecraft 1.18.2 - Fabric 0.14.9

**Comment by AlphaMode** [comment]
Please open a issue on the forge version https://github.com/CompactMods/CompactMachines
